import {sceneAudio} from '../../../lib/native-scene-audio.mjs';
import {magicAtmosphere} from '../../../lib/magic-story.mjs';
import {gameService} from '../../../lib/campaign-access';
import {nativePrincipal} from '../../../server-runtime/native-game.mjs';
import artManifest from '../../../server-data/scene-art.json';
import artWorlds from '../../../server-data/art-world-clocks.json';
import {artProjection} from '../../../lib/scene-art.mjs';
import {preloadPlan} from '../../../lib/media-policy.mjs';
import source from '../../../server-data/game.json';
import {projectMonsterJournal} from '../../../lib/native-story-art.mjs';
import profiles from '../../../server-data/character-sheets.json';
import {projectSheet} from '../../../lib/character-sheet.mjs';
const headers={'Cache-Control':'private, no-store'};
function project(s:Record<string,unknown>){const presentation=s.presentation as {narrative?:string,audio?:{media_id:string}[],preload?:{likely?:string[],alternates?:string[]}} | undefined;const n=source.StoryNodes.find(x=>x.node_id===s.scene_id);const currentArt=artProjection(s,artManifest,artWorlds);return {sceneArt:currentArt,art:currentArt.environment?{...currentArt.environment,id:'dod.current.environment',profile:'dod.pixel32-rgba'}:null,monsterJournal:projectMonsterJournal(s).map(k=>({...k,image:k.image?.id==='dod.journal.actor.troll.living.v1'?{...k.image,src:'/api/art?campaign='+s.campaign_id+'&revision='+s.snapshot_revision+'&slot=journal'}:k.image})),campaign:s.campaign_id,scene:s.scene_id,location:s.location_id,place:n?.title.includes(' — ')?n.title.split(' — ')[0]:s.location_id==='dod.raurin.frontier'?'Raurin frontier':s.location_id==='dod.troll_cave.exterior_transit'?'Outside the Troll Cave':s.location_id==='dod.troll_cave'?'Troll Cave':'Current location',time:s.game_time,revision:s.snapshot_revision,title:n?.title||'Saved expedition',media:sceneAudio(s),preload:preloadPlan({...presentation,audio:sceneAudio(s)}),narrative:presentation?.narrative||n?.player_narrative||'Your party remains at the examined right-route threshold. The control area has not been activated. No hostile contact is recorded.',magicAtmosphere:presentation?.narrative?'':magicAtmosphere(s,n),choices:source.StoryChoices.filter(x=>x.node_id===s.scene_id&&x.visibility==='PLAYER'&&x.active!==false&&x.active!=='FALSE').map(x=>({id:x.choice_id,text:x.player_text})),party:source.Characters.filter(x=>x.campaign_id===s.campaign_id).map(x=>({id:x.character_id,name:x.name,race:x.race,class:x.class_id,hp:x.hp_current,max:x.hp_max,ac:x.armor_class,thac0:x.thac0,saves:JSON.parse(x.saves_json),abilities:JSON.parse(x.abilities_json),sheet:projectSheet(x,source,profiles,s)}))};}
function error(e:unknown){const code=(e as {code?:string}).code;const status=code==='FORBIDDEN'?403:code==='REVISION_CONFLICT'||code==='IDEMPOTENCY_CONFLICT'?409:code==='UNSUPPORTED_ACTION'||code==='INVALID_COMMAND'?400:503;return Response.json({error:status===403?'Sign in with the campaign owner account.':status===409?'The save or receipt changed. Refresh before acting.':status===400?'Review a supported action before submitting.':'Campaign storage is unavailable. Check the journal before retrying.'},{status,headers});}
export async function GET(req:Request){try{const campaign=new URL(req.url).searchParams.get('campaign')||'dod-main';const saved=await gameService().load(nativePrincipal(req),campaign);return Response.json({...project({...saved.raw,snapshot_revision:saved.revision,game_time:Number(saved.raw.game_time)}),journal:saved.journal},{headers});}catch(e){return error(e);}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin||req.headers.get('sec-fetch-site')==='cross-site')return Response.json({error:'Forbidden origin'},{status:403,headers});if(!req.headers.get('content-type')?.startsWith('application/json'))return Response.json({error:'JSON required'},{status:415,headers});const reader=req.body?.getReader();if(!reader)return Response.json({error:'Missing action'},{status:400,headers});let bytes=0,body='';const decoder=new TextDecoder('utf-8',{fatal:true});try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>12000){await reader.cancel();return Response.json({error:'Action too large'},{status:413,headers});}body+=decoder.decode(value,{stream:true});}body+=decoder.decode();}finally{reader.releaseLock();}let input;try{input=JSON.parse(body);}catch{return Response.json({error:'Invalid JSON'},{status:400,headers});}const receipt=await gameService().handle(nativePrincipal(req),input);return Response.json(receipt,{headers});}catch(e){return error(e);}}
