#!/usr/bin/env python3
"""Authoring-only deterministic token compiler. No network or game state access."""
from pathlib import Path
import argparse, json
ROOT=Path(__file__).resolve().parents[1]
def build():
    t=json.loads((ROOT/'assets/theme.tokens.json').read_text())
    lines=['/* Generated by scripts/build_css.py; edit tokens or components, then rebuild. */', '[data-dod-theme="moonlit-ink"] {']
    lines += [f'  --dod-{k}: {v};' for k,v in t['colors'].items()]
    lines += [f'  --dod-{k}: var(--dod-{v});' for k,v in t['roles'].items() if k != v]
    ty=t['typography']; lay=t['layout']
    vals={'font-display':ty['display'],'font-body':ty['body'],'font-reading':ty['reading'],'body-size':ty['body-size'],'body-leading':ty['body-leading'],'reading-width':ty['reading-width'],'touch-target':lay['touch-target'],'content-width':lay['content-width'],'radius':lay['corner-radius'],'art-opacity':t['art']['background_opacity']}
    lines += [f'  --dod-{k}: {v};' for k,v in vals.items()]
    lines += ['}',(ROOT/'assets/components.css').read_text()]
    return '\n'.join(lines)
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    target=ROOT/'assets/theme.css';expected=build()
    if a.check:
        if not target.exists() or target.read_text()!=expected: raise SystemExit('Theme CSS is stale; rebuild it.')
        print('Theme CSS matches tokens and components.')
    else:
        target.write_text(expected);print(target)
