'use client';
import {ScenePlate} from '../components/scene-plate';
import {StoryPlate} from '../components/story-plate';
import Image from 'next/image';
import type {StoryArt} from '../lib/story-art.mjs';
import {useState,useEffect,useEffectEvent,useRef} from 'react';
import {Play,Pause,Square,Volume2,VolumeX,Settings} from 'lucide-react';
import {resolvePresentation} from '../lib/art-engine.mjs';
import {browserHandoff} from '../lib/browser-handoff.mjs';
import sitePresentation from '../lib/site-presentation.json';
import {SoundMixer} from '../components/sound-mixer';
import {defaultMix,readMix,saveMix,type Mix} from '../lib/sound-settings.mjs';
import {SoundSession,type SoundState} from '../lib/campfire-test.mjs';
import {AudioEngine} from '../lib/audio-engine.mjs';
import {createSavePoller} from '../lib/save-poller.mjs';
import {CharacterSheet,type PartyMember} from '../components/character-sheet';
import {Introduction,type IntroductionId} from '../components/introduction';
import {MicrophoneInput} from '../components/microphone-input';
import introductions from '../lib/module-introductions.json';
import {moduleAtEntry,introWasSeen,rememberIntro} from '../lib/module-boundaries.mjs';
const titleTheme={...sitePresentation.background_theme,media_id:'dod.audio.opening_replacement.opening_title_theme_v2',fallback_media_id:'scorefile.campaign_opening_overture.v397'};
type Party=PartyMember;
type Cue={media_id:string,bus:string,loop?:boolean};
type ArtImage={src:string,width:number,height:number,alt:string,mode:string};
type Game={sceneArt?:{environment:ArtImage|null,actor:ArtImage|null,phase:string|null},art?:StoryArt|null,monsterJournal?:{id:string,name:string,location:string,summary:string,image:StoryArt|null,image_caption:string,outcome:string}[],preload?:{current:string[],likely:string[],alternates:string[]},media?:Cue[],campaign:string,scene:string,location:string,place:string,time:number,revision:number,title:string,narrative:string,magicAtmosphere?:string,choices:{id:string,text:string}[],party:Party[],journal:{text:string,status:string,created:string}[]};
export default function Game(){
 const [g,setG]=useState<Game|null>(null),[campaign,setCampaign]=useState('dod-main'),[tab,setTab]=useState('Home'),[viewport,setViewport]=useState(390),[menu,setMenu]=useState(false),[text,setText]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),[listeningTest,setListeningTest]=useState(false),[audioStatus,setAudioStatus]=useState('Sound off'),[selected,setSelected]=useState('party.snogard');
 const [mix,setMix]=useState(defaultMix),[soundState,setSoundState]=useState<SoundState>({mode:'off',state:'stopped',elapsed:0,missing:[]}),[mixSaved,setMixSaved]=useState(true);
 const [introId,setIntroId]=useState<IntroductionId|null>(null),[selectedActions,setSelectedActions]=useState<string[]>([]);
 const [saveStale,setSaveStale]=useState(false);
 const themeSuppressed=useRef(false),themeWanted=useRef(true),themeStarting=useRef(false);
 const mixRef=useRef(mix),session=useRef<SoundSession|null>(null);
 const mixer=useRef<AudioEngine|null>(null),currentGame=useRef<Game|null>(null),presented=useRef(''),audioRequest=useRef(0),requestSequence=useRef(0),activeCampaign=useRef(campaign),tabRef=useRef(tab),sceneRequested=useRef('');activeCampaign.current=campaign;currentGame.current=g;tabRef.current=tab;
 useEffect(()=>{const update=()=>setViewport(window.innerWidth);update();window.addEventListener('resize',update);return ()=>window.removeEventListener('resize',update)},[]);
 function audio(){if(mixer.current)return mixer.current;mixer.current=new AudioEngine(id=>{const q=new URLSearchParams({id,campaign:currentGame.current?.campaign||activeCampaign.current,revision:String(currentGame.current?.revision??0)});return '/api/media?'+q.toString();});mixer.current.applyMix(mixRef.current);mixer.current.setThemeSuppressed(themeSuppressed.current);return mixer.current;}
 function sound(){return session.current??(session.current=new SoundSession(audio(),titleTheme,state=>{setSoundState(state);setPlaying(state.state==='playing');setListeningTest(state.mode==='campfire');setAudioStatus(state.mode==='campfire'?`Campfire ${state.state} · ${state.elapsed}/60s${state.missing.length?' · Unavailable: '+state.missing.join(', '):''}`:state.mode==='scene'?`Scene sound ${state.state}${state.missing.length?' · Missing: '+state.missing.join(', '):''}`:state.mode==='introduction'?`Narrated introduction ${state.state}`:state.elapsed===60?'Campfire complete':state.state==='paused'?'Sound paused':state.state==='playing'?'Website theme playing':'Sound stopped');}));}
 function storage(){try{return window.localStorage;}catch{return null;}}
 function changeMix(bus:string,patch:{volume?:number,enabled?:boolean}){
 const previous=mixRef.current,level=bus==='Master'?{volume:previous.master,enabled:previous.enabled}:previous.layers[bus];
 if(!level||(patch.volume===undefined||patch.volume===level.volume)&&(patch.enabled===undefined||patch.enabled===level.enabled))return;
 const next:Mix=bus==='Master'?{...previous,master:patch.volume??previous.master,enabled:patch.enabled??previous.enabled}:{...previous,layers:{...previous.layers,[bus]:{...level,...patch}}};
 mixRef.current=next;setMix(next);mixer.current?.applyMix(next);setMixSaved(saveMix(storage(),next));
 if(bus!=='Master')void session.current?.layerChanged(bus,level.enabled&&level.volume>0);
 if(bus==='Master'&&next.enabled&&!previous.enabled){themeWanted.current=true;void startWebsiteTheme();}
 }
 async function startWebsiteTheme(){
 if(tabRef.current!=='Home'||!themeWanted.current||!mixRef.current.enabled||(session.current&&session.current.mode!=='off')||themeStarting.current)return;
 themeStarting.current=true;try{const engine=audio();await engine.unlock();if(themeWanted.current&&(!session.current||session.current.mode==='off')){await engine.startTheme(titleTheme);if(!session.current||session.current.mode==='off'){setPlaying(engine.hasAudibleCue('Music'));setAudioStatus(themeSuppressed.current?'Website music paused for mixer':engine.hasAudibleCue('Music')?'Website theme playing':'Website theme unavailable');}}}catch{setAudioStatus('Tap sound On to start audio');}finally{themeStarting.current=false;}
 }
 async function playIntroduction(id:IntroductionId){themeWanted.current=false;mixer.current?.stopTheme?.({fadeSeconds:.2});try{await sound().startIntroduction(introductions[id].media_id);}catch(e){setAudioStatus('Introduction: '+issue(e));}}
 function checkModuleEntry(game:Game|null){if(!game)return false;const id=moduleAtEntry(game.scene) as IntroductionId|null;if(!id||introWasSeen(storage(),game.campaign,id))return false;rememberIntro(storage(),game.campaign,id);setIntroId(id);void playIntroduction(id);return true;}
 async function startSceneAudio(game=currentGame.current,{force=false}:{force?:boolean}={}){if(!game||!mixRef.current.enabled)return;const key=game.campaign+':'+game.revision;if(!force&&sceneRequested.current===key&&sound().mode==='scene'&&['loading','playing'].includes(sound().state))return;themeWanted.current=false;mixer.current?.stopTheme?.({fadeSeconds:.2});if(force){sound().stop();sceneRequested.current='';presented.current='';}sceneRequested.current=key;presented.current='';try{await sound().startScene(game.media||[]);presented.current=key;}catch(e){if(sceneRequested.current===key)sceneRequested.current='';setAudioStatus('Tap Play to start scene audio · '+issue(e));throw e;}}
 function navigate(next:string){const previous=tabRef.current;setMenu(false);tabRef.current=next;if(next==='Explore'){themeWanted.current=false;mixer.current?.stopTheme?.({fadeSeconds:.2});setIntroId('explore');setTab('Explore');void playIntroduction('explore');return}if(next==='Scene'){themeWanted.current=false;sound().stop();sceneRequested.current='';presented.current='';mixer.current?.stopTheme?.({fadeSeconds:.2});setTab('Scene');if(checkModuleEntry(currentGame.current))return;void startSceneAudio(currentGame.current,{force:true}).catch(()=>{});return}if(next==='Home'){sound().stop();sceneRequested.current='';setIntroId(null);themeWanted.current=true;setTab('Home');queueMicrotask(()=>void startWebsiteTheme());return}if(previous==='Home'){themeWanted.current=false;mixer.current?.stopTheme?.({fadeSeconds:.2});}if(introId){sound().stop();setIntroId(null);}setTab(next);}
 function finishIntroduction(){sound().stop();setIntroId(null);tabRef.current='Scene';setTab('Scene');void startSceneAudio(currentGame.current).catch(()=>{});}
 function issue(e:unknown){return e instanceof Error?e.message:'Please try again.';}
 async function load(id=campaign){const sequence=++requestSequence.current;const r=await fetch('/api/game?'+new URLSearchParams({campaign:id}),{cache:'no-store',credentials:'same-origin'});if(r.headers.get('content-type')?.includes('text/html'))throw Error('Your session needs refreshing. Reopen the Site in your browser.');const d=await r.json() as Game & {error?:string};if(!r.ok)throw Error(d.error||'Your saved expedition is temporarily unavailable.');if(sequence===requestSequence.current&&id===activeCampaign.current){setG(d);setSaveStale(false);}}
 const loadFromEffect=useEffectEvent((id:string)=>load(id));
 const themeFromEffect=useEffectEvent(()=>startWebsiteTheme());
 const sceneFromEffect=useEffectEvent(()=>{
 const game=currentGame.current;if(!game)return Promise.resolve();const key=game.campaign+':'+game.revision;
 if((sceneRequested.current===key&&['loading','playing'].includes(sound().state))||(presented.current===key&&soundState.mode==='scene'&&playing))return Promise.resolve();
 return startSceneAudio(game);
 });
 useEffect(()=>{queueMicrotask(()=>{setG(null);setNotice('');setPlaying(false);setListeningTest(false);setAudioStatus('Sound off');});loadFromEffect(campaign).catch(e=>setNotice(issue(e)));session.current?.stop();mixer.current?.stop();presented.current='';audioRequest.current++;},[campaign]);
 useEffect(()=>{
 const poller=createSavePoller({load:()=>loadFromEffect(campaign),isVisible:()=>document.visibilityState!=='hidden',onStatus:({stale}:{stale:boolean})=>setSaveStale(stale)});
 const visibility=()=>poller.visibilityChanged();document.addEventListener('visibilitychange',visibility);poller.start();
 return ()=>{poller.stop();document.removeEventListener('visibilitychange',visibility);};
 },[campaign]);
 useEffect(()=>{const saved=readMix(storage());mixRef.current=saved;queueMicrotask(()=>setMix(saved));mixer.current?.applyMix(saved);
 if(tabRef.current==='Home')void themeFromEffect();const gesture=()=>{if(mixer.current?.context?.state!=='running'){themeStarting.current=false;if(tabRef.current==='Home')void themeFromEffect();else if(tabRef.current==='Scene'&&currentGame.current&&session.current?.mode==='scene'&&session.current.state==='error')void sceneFromEffect().catch(()=>{});}};
 window.addEventListener('pointerdown',gesture);window.addEventListener('keydown',gesture);return()=>{window.removeEventListener('pointerdown',gesture);window.removeEventListener('keydown',gesture);};},[]);
 useEffect(()=>{themeSuppressed.current=tab!=='Home'||menu||soundState.mode==='campfire';mixer.current?.setThemeSuppressed(themeSuppressed.current);if(tab!=='Home'){mixer.current?.stopTheme?.({fadeSeconds:.2});return;}
 if(!themeSuppressed.current&&themeWanted.current&&mixer.current?.context?.state==='running'&&soundState.mode==='off')void themeFromEffect();},[tab,menu,soundState.mode]);
 // Playback controls are not presentation revisions. Pause/Stop must not trigger autostart.
 useEffect(()=>{if(tab!=='Scene'||introId||!mix.enabled)return;void sceneFromEffect().catch(()=>{});},[tab,g?.campaign,g?.revision,introId,mix.enabled]);
 useEffect(()=>{if(soundState.mode==='scene'&&playing&&!listeningTest&&g?.preload)void audio().preload(g.preload).catch(()=>{});},[g,playing,listeningTest,soundState.mode]);
 useEffect(()=>()=>{session.current?.stop();void mixer.current?.dispose();},[]);
 function stop(){themeWanted.current=false;audioRequest.current++;presented.current='';sceneRequested.current='';sound().stop();}
 function stopCampfire(){sound().stop();themeWanted.current=true;}
 async function campfire(){themeWanted.current=true;try{await sound().startCampfire();}catch(e){setAudioStatus('Sound: '+issue(e));}}
 async function sceneSound(){if(!g)return;const key=g.campaign+':'+g.revision;try{if(sound().mode==='scene'&&sound().state==='playing'&&presented.current===key)await sound().pause();else if(sound().mode==='scene'&&sound().state==='paused'&&presented.current===key)await sound().resume();else await startSceneAudio(g);}catch(e){setAudioStatus('Scene sound: '+issue(e));}}
 async function pause(){try{if(tabRef.current==='Home'&&sound().mode==='off'){themeWanted.current=false;await audio().pause();setPlaying(false);setAudioStatus('Website theme paused');}else await sound().pause();}catch(e){setAudioStatus('Sound: '+issue(e));}}
 async function resume(){try{if(sound().state==='paused')await sound().resume();else if(tabRef.current==='Home'&&!menu){themeWanted.current=true;await startWebsiteTheme();}else if(tabRef.current==='Scene'&&currentGame.current)await startSceneAudio(currentGame.current);}catch(e){setAudioStatus('Sound: '+issue(e));}}
 function soundActions(){return <><div className="soundcontrols"><button className="gold" disabled={soundState.state==='loading'} onClick={soundState.mode==='campfire'?stopCampfire:campfire}>{soundState.mode==='campfire'?'Stop Campfire Test':'Campfire Test · 60s'}</button></div><p className="mixer-status" role="status">{audioStatus}</p>{soundState.mode==='campfire'&&<progress className="campfire-progress" aria-label="Campfire Test progress" max="60" value={soundState.elapsed}/>} {!mixSaved&&<p className="muted">Mix active. This browser could not save your preferences.</p>}</>;}
 async function act(value:string,choice?:string){if(!g||busy)return;setBusy(true);mixer.current?.cancelSpeculative();try{const r=await fetch('/api/game',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),campaign,revision:g.revision,text:value,choice})});if(r.headers.get('content-type')?.includes('text/html'))throw Error('Your session needs refreshing. Your action was not confirmed.');const d=await r.json() as {error?:string,message:string};if(!r.ok)throw Error(d.error||'Your action could not be confirmed.');setNotice(d.message);setText('');setSelectedActions([]);await load();}catch(e){setNotice(issue(e));}finally{setBusy(false);}}
 function toggleAction(id:string){setSelectedActions(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 async function submitAction(){if(!g||busy)return;const chosen=g.choices.filter(c=>selectedActions.includes(c.id)),free=text.trim();if(!chosen.length&&!free)return;const value=[...chosen.map(c=>c.text),free].filter(Boolean).join(' + ');const choice=chosen.length===1&&!free?chosen[0].id:undefined;await act(value,choice);}
 async function copyCheckpoint(){if(!g)return;const summary=browserHandoff(g);try{await navigator.clipboard.writeText(summary);setNotice('Checkpoint copied. Paste it into your Desert of Desolation chat. Saves are not automatically synchronized.');}catch{setHandoff(summary);setNotice('Select and copy the checkpoint below, then paste it into your chat.');}}
 const [handoff,setHandoff]=useState('');
 const presentation=resolvePresentation({surface:tab==='Home'?'HOME':tab==='Journal'?'JOURNAL':tab==='Party'?'INVENTORY':'EXPLORATION',viewportWidth:viewport});
 useEffect(()=>{setSelectedActions([]);setText('');},[g?.campaign,g?.revision,g?.scene]);
 const pc=g?.party.find(x=>x.id===selected)||g?.party[0];
 const audioDock=<div className="audio-dock"><div className="audio-transport"><button className="audio-icon-button" disabled={soundState.state==='loading'} onClick={playing?pause:resume} aria-label={playing?'Pause sound':'Play sound'} title={playing?'Pause sound':'Play sound'}>{playing?<Pause aria-hidden="true"/>:<Play aria-hidden="true"/>}</button><button className="audio-icon-button" onClick={stop} aria-label="Stop sound" title="Stop sound"><Square aria-hidden="true"/></button></div><p role="status">{!mix.enabled?'Muted · ':''}{audioStatus}</p><button className="site-sound-toggle" role="switch" aria-label="Game sound" aria-checked={mix.enabled} title={mix.enabled?'Turn sound off':'Turn sound on'} onClick={()=>{const enabled=!mixRef.current.enabled;changeMix('Master',{enabled});if(enabled){themeStarting.current=false;if(tabRef.current==='Home')void startWebsiteTheme();else if(tabRef.current==='Scene'&&currentGame.current)void startSceneAudio(currentGame.current)}}}><span className="sound-switch-track" aria-hidden="true"><span className="sound-switch-thumb">{mix.enabled?<Volume2/>:<VolumeX/>}</span></span></button></div>;
 return <main data-dod-theme="moonlit-ink" data-view={tab.toLowerCase()} data-art-mode={presentation.mode} data-art-layout={presentation.layout}>
 <header className="game-header"><div className="header-tools"><Image src="/logos/icon-white.png" alt="Eye of Horus" width="44" height="44" unoptimized/><button className="menu-toggle" aria-label="Settings" title="Settings" aria-expanded={menu} aria-controls="expedition-menu" onClick={()=>setMenu(v=>!v)}><Settings aria-hidden="true"/></button></div></header>
 {menu&&<section id="expedition-menu" className="expedition-menu" aria-label="Settings"><div className="menu-carving" data-dod-site-ornament="true" aria-hidden="true">𓆣 · 𓇉 · 𓆣</div><label htmlFor="campaign">Saved expedition</label><select id="campaign" value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="dod-main">Main campaign</option><option value="dod-demo-001">Saved demo</option></select><button onClick={()=>load().catch(e=>setNotice(issue(e)))}>Refresh save</button><span className="menu-record">Site record · Revision {g?.revision??'—'}</span><button disabled={!g} onClick={copyCheckpoint}>Copy checkpoint for ChatGPT</button><details className="menu-sound" open><summary>Sound &amp; ambience</summary><SoundMixer prefix="menu-mix" mix={mix} onChange={changeMix}/>{soundActions()}{introId&&<button onClick={()=>playIntroduction(introId)}>Replay narration</button>}{audioDock}</details></section>}
 {saveStale&&<p role="status" className="notice">Save refresh failed; the displayed revision may be stale. Use Settings to refresh the save.</p>}
 {notice&&<p role="status" className="notice">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}>Close</button></p>}
 {handoff&&<section className="notice"><label htmlFor="handoff">Checkpoint for ChatGPT</label><textarea id="handoff" readOnly value={handoff} onFocus={e=>e.currentTarget.select()}/><button onClick={()=>setHandoff('')}>Close checkpoint</button></section>}
 <div className="layout"><section className="game">
 {tab==='Home'?<section className="dod-home"><div className="home-hero"><Image src="/art/title-landscape.png" alt="" width="1536" height="1024" priority unoptimized/><div className="home-lockup"><h2><Image className="title-wordmark" src="/art/desert-title.svg" alt="Desert of Desolation" width="2172" height="724" unoptimized/></h2><small className="home-seekers">THE SEEKERS OF RA</small></div></div><div className="home-actions"><button className="tomb-entry" disabled={!g} onClick={()=>navigate('Scene')} aria-label="Begin or resume the current scene"><Image src="/art/open-tomb-doorway.png" alt="A glowing open tomb doorway" fill sizes="(max-width: 600px) 84vw, 360px" unoptimized/></button></div></section>
 :tab==='Explore'?<Introduction id="explore" onContinue={()=>navigate('Scene')}/>
 :introId?<Introduction id={introId} onContinue={finishIntroduction}/>
 :!g?<div className="loading"><p>Loading your saved expedition…</p><button onClick={()=>load().catch(e=>setNotice(issue(e)))}>Retry</button></div>
 :tab==='Scene'?<><div className="sceneheading"><small>{campaign==='dod-main'?'MAIN EXPEDITION':'SAVED DEMO'}</small><h2>{g.title}</h2></div><ScenePlate art={g.sceneArt}/><article className="dod-panel dod-narration">{g.narrative.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}{g.magicAtmosphere?<p>{g.magicAtmosphere}</p>:null}</article><div className="choices" aria-label="Available actions"><h3>Select one or more actions</h3>{g.choices.map((c,i)=>{const picked=selectedActions.includes(c.id);return <button type="button" key={c.id} disabled={busy} aria-pressed={picked} data-selected={picked?'true':'false'} onClick={()=>toggleAction(c.id)}><span>{String(i+1).padStart(2,'0')}</span>{c.text}</button>})}{selectedActions.length>0?<p className="muted">{selectedActions.length} selected. Submit when ready.</p>:null}</div><form onSubmit={e=>{e.preventDefault();void submitAction();}}><label htmlFor="action">Optional details or a different action</label><textarea id="action" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Add details, combine the selected actions, or describe something else."/><button className="gold" disabled={busy||(!text.trim()&&selectedActions.length===0)}>{busy?'Saving…':selectedActions.length?('Submit '+selectedActions.length+' selected action'+(selectedActions.length===1?'':'s')):'Submit action'}</button></form><p className="muted">Most actions are saved for adjudication and do not advance the expedition. Use Menu → Copy checkpoint for ChatGPT to share the record manually. ChatGPT outcomes are not automatically saved here.</p></>
 :tab==='Party'?<><div className="sceneheading"><small>THE SEEKERS OF RA</small><h2>Your company</h2></div><div className="roster">{g.party.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} aria-pressed={selected===p.id}>{p.name}<small>{p.hp} / {p.max} HP</small></button>)}</div>{pc&&<CharacterSheet key={g.campaign+pc.id} member={pc} revision={g.revision}/>}</>
 :<><div className="sceneheading"><small>EXPEDITION RECORD</small><h2>Journal</h2></div><StoryPlate art={g.art} caption={g.title} compact/><section className="monster-ledger" aria-label="Slain creatures"><h3>Slain creatures</h3>{g.monsterJournal?.length?<div className="monster-cards">{g.monsterJournal.map(m=><article className="monster-card dod-panel" key={m.id}><StoryPlate art={m.image} caption={m.image_caption}/><div><small>{m.location} · {m.outcome}</small><h4>{m.name}</h4><p>{m.summary}</p>{!m.image&&<p className="muted">Living-form portrait unavailable.</p>}</div></article>)}</div>:<p className="muted">No confirmed kills in this expedition.</p>}</section><h3 className="journal-actions-title">Expedition notes</h3>{g.journal.length?g.journal.map((a,i)=><section className="entry dod-panel" key={i}><small>{new Date(a.created).toLocaleString()}</small><p>{a.text}</p><strong>{a.status.startsWith('RESOLVED')?'Resolved and saved':'Awaiting adjudication'}</strong></section>):<p className="muted">No website actions yet. Your checkpoint is preserved.</p>}</>}
 </section></div>
 <MicrophoneInput enabled={tab==='Scene'} onTranscript={value=>setText(current=>[current.trim(),value.trim()].filter(Boolean).join(' ').slice(0,2000))} onStatus={setNotice}/>
 <div className="site-utility">
 <details className="legal-disclosure"><summary>Publisher &amp; legal notices</summary><footer className="legal-footer dod-footer"><div className="brand-logos" aria-label="Original game and publisher logos"><Image src="/branding/adnd.png" alt="Advanced Dungeons & Dragons" width="1105" height="334" unoptimized/><Image src="/branding/adnd-2e.png" alt="Advanced Dungeons & Dragons 2nd Edition" width="1104" height="302" unoptimized/><Image className="publisher-logo" src="/branding/wizards.png" alt="Wizards of the Coast" width="1600" height="1600" unoptimized/><Image className="publisher-logo tsr-logo" src="/branding/tsr.png" alt="TSR, Inc." width="1600" height="1600" unoptimized/></div><p>DUNGEONS &amp; DRAGONS, D&amp;D, Wizards of the Coast, Forgotten Realms, the dragon ampersand, Player’s Handbook, Monster Manual, Dungeon Master’s Guide, D&amp;D Adventurers League, all other Wizards of the Coast product names, and their respective logos are trademarks of Wizards of the Coast in the USA and other countries.</p><p>This work contains material that is copyright Wizards of the Coast and/or other authors. Such material is used with permission under the Community Content Agreement for Dungeon Masters Guild.</p><p>All other original material in this work is copyright © 2026 by C F and published under the Community Content Agreement for Dungeon Masters Guild.</p></footer></details></div>
 <div className="mobile-dock"><nav aria-label="Game views">{['Scene','Party','Journal'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>navigate(t)}>{t}</button>)}</nav></div>
 </main>
}
