import characterAliases from '../lib/character-aliases.json';
import type {ReactNode} from 'react';
import templates from '../server-data/party-sheet-templates.json';
export type Sheet = {template:string;scores:Record<string,unknown>|null;saves:Record<string,unknown>|null;sections:{magic:boolean;thieving:boolean;turnUndead:boolean;martialArts:boolean};[key:string]:unknown};
export type PartyMember = {id:string;name:string;race:string;class:string;hp:number;max:number;ac:number;thac0:number;abilities:Record<string,unknown>;sheet:Sheet};
const themes=templates.actors as Record<string,{name:string;title:string;portrait:string;symbol?:string}>;
const label=(key:string)=>key.replaceAll('_',' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\bpct\b/g,'%').replace(/\b\w/g,c=>c.toUpperCase());
function Value({value}:{value:unknown}) {
 if(value==null||value==='')return <span className="sheet-unknown">—</span>;
 if(Array.isArray(value))return value.length?<ul className="sheet-list">{value.map((v,i)=><li key={i}><Value value={v}/></li>)}</ul>:<span className="sheet-unknown">None recorded</span>;
 if(typeof value==='object'){const entries=Object.entries(value as Record<string,unknown>).filter(([k])=>!['applicable','power_id','spell_id','initial_remaining'].includes(k));return entries.length?<dl className="sheet-fields">{entries.map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd><Value value={v}/></dd></div>)}</dl>:<span className="sheet-unknown">Not recorded</span>;}
 return <span>{typeof value==='boolean'?(value?'Yes':'No'):String(value)}</span>;
}
function Block({title,children,id}:{title:string;children:ReactNode;id?:string}){return <section className="record-block" id={id}><h3>{title}</h3><div className="record-content">{children}</div></section>;}
function Fields({fields}:{fields:[string,unknown][]}){return <dl className="sheet-fields">{fields.map(([k,v])=><div key={k}><dt>{k}</dt><dd><Value value={v}/></dd></div>)}</dl>;}
function Records({rows,columns}:{rows:unknown;columns:[string,string][]}) {
 const records=Array.isArray(rows)?rows:[];
 if(!records.length)return <p className="sheet-unknown">No verified entries recorded.</p>;
 return <div className="record-rows">{records.map((row,i)=><dl className="record-row" data-columns={columns.length} key={i}>{columns.map(([key,title])=><div key={key}><dt>{title}</dt><dd><Value value={(row as Record<string,unknown>)[key]}/></dd></div>)}</dl>)}</div>;
}
function Magic({value}:{value:unknown}){
 const magic=(value||{}) as Record<string,unknown>;
 return <><h4>Prepared spells</h4><Records rows={magic.prepared_spells} columns={[["spell","Spell"],["prepared","Prepared"],["expended","Used"],["available","Available"]]}/><h4>Spell slots & capacity</h4><Records rows={magic.spell_slots} columns={[["type","Class"],["level","Level"],["maximum","Maximum"],["used","Used"],["bonus","Bonus"],["available","Available"]]}/>{magic.fetched_cache?<><h4>Fetched copies</h4><Records rows={magic.fetched_cache} columns={[["spell","Spell"],["remaining","Remaining"],["execution","Casting requirement"]]}/><Fields fields={[["Retrieval",magic.retrieval]]}/></>:null}{magic.spell_summary?<Fields fields={[["Recorded magic",magic.spell_summary]]}/>:null}{magic.casting_access?<Fields fields={[["Class access",magic.casting_access],["Recovery",magic.recovery]]}/>:null}{magic.powers?<details className="sheet-reference"><summary>Magic powers & familiar uses</summary><Value value={magic.powers}/></details>:null}{magic.knowledge?<details className="sheet-reference"><summary>Spell knowledge & detailed mechanics</summary><Value value={magic.knowledge}/></details>:null}{magic.recommendations?<details className="sheet-reference"><summary>Spells to consider learning or preparing</summary><Value value={magic.recommendations}/></details>:null}{magic.limits?<details className="sheet-reference"><summary>Competitive magic limits</summary><Value value={magic.limits}/></details>:null}<p className="sheet-unknown">Only verified preparations and fetched spells are listed. Blank entries do not grant a spell.</p></>;
}
export function CharacterSheet({member,revision}:{member:PartyMember;revision:number}) {
 const s=member.sheet,theme=themes[(characterAliases.alias_to_canonical as Record<string,string>)[member.id]||member.id]||{name:'unrecorded',title:'Character record',portrait:null,symbol:''};
 const sectionLinks=[['record-combat','Combat'],['record-equipment','Gear'],...(s.sections.magic?[['record-magic','Magic']]:[]),...(s.sections.thieving?[['record-thieving','Thievery']]:[]),['record-notes','Notes']];
 return <article className="sheet full-sheet master-sheet" data-sheet-theme={theme.name} aria-label={`${member.name} character sheet`}>
  <header className="record-header"><div><small><span className="egyptian-symbol" aria-hidden="true">{theme.symbol}</span> THE SEEKERS OF RA · CHARACTER RECORD</small><h2>{member.name}</h2><p className="record-role">{theme.title}</p><p>{member.race} · {member.class} · <Value value={s.alignment}/></p><small>PLAYER CHARACTER RECORD · Rev 4.6 · Save {revision}</small></div><figure className="record-portrait">{theme.portrait?<img src={`/art/party/${theme.portrait}.png`} alt={`Ink portrait of ${member.name}`} width="1254" height="1254" loading="lazy" onError={e=>{e.currentTarget.hidden=true;e.currentTarget.parentElement?.classList.add('portrait-unavailable')}}/>:<span>Portrait unavailable</span>}</figure></header>
  <nav className="record-index" aria-label="Character sheet sections">{sectionLinks.map(([id,name])=><a key={id} href={`#${id}`}>{name}</a>)}</nav>
  <div className="record-top-grid"><Block title="Character description"><Fields fields={[["Class / kit / level",member.class],["Race",member.race],["Alignment",s.alignment],["Age",s.age],["Patron deity / religion",s.faith],["Place of origin",s.origin],["Current location",typeof s.location==='string'?s.location.replace(/^dod\./,'').replaceAll('.',' · ').replaceAll('_',' '):s.location],["Personality",s.personality]]}/></Block><Block title="Ability scores"><div className="ability-ledger">{['STR','DEX','CON','INT','WIS','CHA'].map(k=><div key={k}><span>{k}</span><strong><Value value={s.scores?.[k]}/></strong></div>)}</div>{s.modifiers?<details className="sheet-reference"><summary>Ability modifiers</summary><Value value={s.modifiers}/></details>:null}</Block><Block title="Saving throws"><div className="saving-ledger">{[['PPDM','Paralysis / poison / death'],['RSW','Rod / staff / wand'],['PP','Petrification / polymorph'],['BW','Breath weapon'],['Spells','Spell']].map(([k,n])=><div key={k}><span>{n}</span><strong><Value value={s.saves?.[k]}/></strong></div>)}</div></Block></div>
  <Block title="Combat" id="record-combat"><div className="sheet-vitals">{[['Hit points',`${member.hp} / ${member.max}`],['Armor class',member.ac],['THAC0',member.thac0],['Move',s.movement]].map(([k,v])=><div key={String(k)}><span>{String(k)}</span><strong><Value value={v}/></strong></div>)}</div><Fields fields={[["Initiative",s.initiative],["Attacks per round",s.attacks],["Hit dice",s.hitDice],["Surprised / shieldless / rear AC",s.armorVariants],["Armor worn",s.armor],["To hit / damage / AC modifiers",s.combatModifiers]]}/></Block>
  <Block title="Weapon combat"><Records rows={s.weapons} columns={[["weapon","Weapon"],["qty","Quantity"],["attacks","# AT"],["size","Size"],["type","Type"],["speed","Base speed"],["adjustment","Hit / damage adj."],["damage","Damage"],["range","Range / special"]]}/></Block>
  <Block title="Proficiencies"><Value value={s.proficiencies}/></Block>
  <Block title="Character class / kit information"><Fields fields={[["Special powers / benefits",s.special],["Recorded class notes",s.classNotes]]}/></Block>
  {s.sections.thieving?<Block title="Thieving abilities" id="record-thieving"><Value value={s.thieving}/></Block>:null}
  {s.sections.turnUndead?<Block title="Priest versus undead"><Value value={s.turnUndead}/><p className="sheet-unknown">Unrecorded targets and modifiers require rules resolution.</p></Block>:null}
  {s.sections.magic?<Block title="Wizard & priest spells" id="record-magic"><Magic value={s.magic}/></Block>:null}
  <Block title="Equipment" id="record-equipment"><Records rows={s.inventory} columns={[["name","Item"],["quantity","Quantity"],["slot","Location / slot"],["weight","Weight"],["charges","Charges"]]}/><Fields fields={[["Total carried weight",s.totalWeight],["Encumbrance",s.encumbrance]]}/></Block>
  <div className="record-pair"><Block title="Magic items">{Array.isArray(s.magicItems)?s.magicItems.map((item,i)=><details className="sheet-reference" key={i}><summary>{typeof item==='string'?item:String(item.item||'Magic item')}</summary><Value value={item}/></details>):<Value value={s.magicItems}/>}</Block><Block title="Treasure / other possessions"><Value value={s.treasure}/></Block><Block title="Movement"><Fields fields={[["Base movement",s.movement],["Recorded movement adjustments",s.movementAdjustments]]}/></Block><Block title="Experience"><Fields fields={[["Total XP",s.xp],["XP needed for next level",s.nextLevelXp]]}/></Block></div>
  <Block title="Henchmen / animal companions"><Value value={s.companions}/>{Array.isArray(s.mounts)&&s.mounts.length?<Fields fields={[["Recorded mounts",s.mounts]]}/>:null}</Block>
  {s.sections.martialArts?<Block title="Combat style & maneuvers"><Value value={s.martialArts}/></Block>:null}
  <Block title="Wounds / active effects"><Fields fields={[["Conditions & wounds",s.conditions],["Recorded injury",s.injury],["Active effects",s.effects]]}/></Block>
  <Block title="Magic, knowledge & character actions"><Value value={s.magicCharacter&&typeof s.magicCharacter==='object'?Object.fromEntries(Object.entries(s.magicCharacter).filter(([k])=>k!=='abilities'||!s.sections.magic)):s.magicCharacter}/></Block><Block title="Background / history / noteworthy events" id="record-notes"><Value value={s.publicNotes}/></Block>
  <details className="record-block sheet-reference"><summary>2E rules & campaign ledger</summary><Value value={s.rulesCompletion}/></details><footer className="record-footer"><p>Recorded state is retained. Generated scores and derived 2E references are identified in the rules ledger; campaign exceptions remain explicit. — = not recorded. Base weapon figures exclude magic and situational adjustments.</p><small>Layout adapted from AD&D Character Sheet Rev 4.6 by Patrick M. Murphy (7/98). Desert of Desolation · {theme.title}.</small></footer>
 </article>;
}
