'use client';
import Image from 'next/image';
import {useMemo,useState} from 'react';
import characterAliases from '../../data/CHARACTER_ALIASES.json';
export type PartyMember={id:string,name:string,hp:number,max:number,[key:string]:unknown};
const portraits:Record<string,string>={'party.snogard':'/character-sheet/snogard.png','party.malekith':'/character-sheet/azhar.png','party.vaelis':'/character-sheet/dakarai.png','party.syrra':'/character-sheet/cyrra.png','party.tal':'/character-sheet/eryon.png','party.zarvak':'/character-sheet/barak.png'};
const aliasMap=characterAliases.alias_to_canonical as Record<string,string>;const canonicalId=(id:string)=>aliasMap[id]||id;
const order=['Overview','Abilities','Combat','Skills','Equipment','Magic','Companions','Notes'] as const;type Group=typeof order[number];
function groupFor(key:string):Group{const k=key.toLowerCase();if(/^(str|dex|con|int|wis|cha)|ability|abilities|attribute/.test(k))return 'Abilities';if(/hp|armor|ac$|attack|save|weapon|combat|initiative/.test(k))return 'Combat';if(/skill|proficien|thief|stealth|language/.test(k))return 'Skills';if(/inventory|equipment|gear|armor|weapon|item|coin|gold/.test(k))return 'Equipment';if(/spell|magic|scroll|wand|staff|ring|amulet/.test(k))return 'Magic';if(/familiar|companion|mount|animal/.test(k))return 'Companions';return 'Notes';}
function show(v:unknown){if(v===null||v===undefined)return '—';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);try{return JSON.stringify(v,null,2)}catch{return String(v)}}
export function CharacterSheet({member,revision}:{member:PartyMember,revision:number}){const portrait=portraits[canonicalId(member.id)]||null;const grouped=useMemo(()=>{const g:Record<Group,[string,unknown][]>={Overview:[['HP',`${member.hp} / ${member.max}`],['Revision',revision]],Abilities:[],Combat:[],Skills:[],Equipment:[],Magic:[],Companions:[],Notes:[]};for(const [k,v] of Object.entries(member)){if(['id','name','hp','max'].includes(k))continue;g[groupFor(k)].push([k,v]);}return g},[member,revision]);const tabs=order.filter(t=>grouped[t].length);const [tab,setTab]=useState<Group>(tabs[0]||'Overview');const active=tabs.includes(tab)?tab:(tabs[0]||'Overview');return <section className="full-sheet master-sheet" aria-label={`${member.name} character sheet`}><header className="record-header"><figure className="record-portrait-fullbody">{portrait?<Image src={portrait+'?v=alpha38'} alt={`${member.name} full-body character render`} width={1254} height={1254} unoptimized/>:<div className="portrait-unavailable" role="img" aria-label={`${member.name} portrait unavailable`}>Portrait unavailable</div>}</figure><div><h2>{member.name}</h2><p>{member.hp} / {member.max} HP</p></div></header><div className="sheet-tabs" role="tablist" aria-label="Character sheet sections">{tabs.map(t=><button key={t} role="tab" aria-selected={active===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tabs.map(t=><section key={t} role="tabpanel" hidden={active!==t}><dl>{grouped[t].map(([k,v])=><div className="record-row" key={k}><dt>{k}</dt><dd><pre>{show(v)}</pre></dd></div>)}</dl></section>)}</section>}
